#!/usr/bin/bash

. "$SHLIB_PATH"

release_basever=$(ca | fl | vsort | tail -n1)
unstable_basever=$(cr | grep $name | cut -d\" -f8 | grep -Ev 'diff|patches|doc|<' | vtrim -re 's,.tar.gz(|.sig)$,,' | fsl | vsort | tail -n1)

# there is no prerelease version
if [[ "$release_basever" == "$unstable_basever" ]]; then
    upstream="${upstream%\?*}/bash-$release_basever-patches/?C=M;O=D"
    patch=$(cr | grep -Eo 'bash[0-9]+-[0-9]{3}' | uniq | cut -d- -f2 | sed 's,^0*,,' | vsort | tail -n1)
    echo "$release_basever.$patch"
    exit 0
fi

# there is a prerelease version
echo "$unstable_basever"
