#!/usr/bin/env bash

log() {
    local now_ms elapsed_ms hours minutes seconds millis elapsed
    now_ms=$(date +%s%N)
    now_ms=${now_ms:0:13}
    elapsed_ms="$((now_ms - start_time_ms))"

    hours=$((elapsed_ms / 3600000))
    minutes=$((elapsed_ms % 3600000 / 60000))
    seconds=$((elapsed_ms % 60000 / 1000))
    millis=$((elapsed_ms % 1000))

    if (( hours > 0 )); then
        printf -v elapsed "%02d:%02d:%02d.%03dms" "$hours" "$minutes" "$seconds" "$millis"
    elif (( minutes > 0 )); then
        printf -v elapsed "%02d:%02d.%03d" "$minutes" "$seconds" "$millis"
    else
        printf -v elapsed "%d.%03d" "$seconds" "$millis"
    fi

    printf "%8s [VAT] %s\n" "$elapsed" "$1" >&"${2:-2}"
}

# Sanity check
if [ ! -d p ]; then
    log "Execute vat from the source directory"
    exit 2
fi

# Read config and set up environment
. lib/vars
. lib/config
export NO_CACHE GUARANTEE DRY

# Record start times
start_time_ns=$(date +%s%N)
start_time_ms="${start_time_ns:0:13}"
start_time="${start_time_ms:0:10}"

# Increment runcount
runcount=$(<runcount)
((runcount++))
log "VAT v$(<version) beginning run #$(<runcount)"
$DRY || echo $runcount > runcount
unset runcount

# Handle caching
if [ -f "$VAT_CACHE/timestamp" ]; then
    modtime=$(stat -c %Y "$VAT_CACHE/timestamp")
    diff=$((start_time - modtime))
else
    diff=0
    install -Dm644 /dev/null "$VAT_CACHE/timestamp"
fi

# Clear old logs
rm -rf "$VAT_TARGET/logs"

if [ $diff -gt $CACHE_LIFESPAN ]; then
    log "Clearing cache ($diff seconds old)"
    rm -rf $VAT_CACHE
    install -Dm644 /dev/null "$VAT_CACHE/timestamp"
else
    log "Not clearing cache ($diff seconds old)"
fi

# Collect projects if none were specified
declare -a projects
projects=("$@")

if [ "${#projects[@]}" -eq 0 ]; then
    log "Collecting projects"
    readarray -t projects < <(find p -type f -name config | sed -e 's,^p/,,' -e 's,/config$,,')
fi

# Spawn jobs
# TODO: Limit the number of jobs that may run at once
jobs=()
for project in "${projects[@]}"; do
    log "Fetching $project"

    (
        log_file_out="$VAT_TARGET/logs/$project/out"
        log_file_err="$VAT_TARGET/logs/$project/err"
        log_file_dbg="$VAT_TARGET/logs/$project/dbg"
        install -Dm644 /dev/null "$log_file_out"
        install -Dm644 /dev/null "$log_file_err"
        install -Dm644 /dev/null "$log_file_dbg"
        exec 1> "$log_file_out"
        exec 2> "$log_file_err"
        exec 3> "$log_file_dbg"
        libexec/runner "$project"
        exec 1>&-
        exec 2>&-
        exec 3>&-
    ) &
    jobs+=($!)
done

# Reap jobs
status=0
for pid in "${jobs[@]}"; do
    if ! wait $pid; then
        status=1
    fi
done

# Log completion
log "Processed ${#jobs[@]} projects"

# Consolidate logs
log "Consolidating logs"
all_base="$VAT_TARGET/logs/ALL"
all_out="$all_base.out"
all_err="$all_base.err"
all_dbg="$all_base.dbg"
install -Dm644 /dev/null "$all_out"
install -Dm644 /dev/null "$all_err"
install -Dm644 /dev/null "$all_dbg"

find $VAT_TARGET/logs -type f -name 'out' ! -name 'ALL.out' | sort | while read -r log_out; do
    cat "$log_out" >> "$all_out"
done

find $VAT_TARGET/logs -type f -name 'err' ! -name 'ALL.err' | sort | while read -r log_err; do
    cat "$log_err" >> "$all_err"
done

find $VAT_TARGET/logs -type f -name 'dbg' ! -name 'ALL.dbg' | sort | while read -r log_dbg; do
    cat "$log_dbg" >> "$all_dbg"
done

log "Logs available at $all_base.*"

libexec/record
libexec/report "${projects[@]}" | tee "$VAT_TARGET/report"

if $DRY; then
    echo
    log "Cleaning artifacts after dry run"
    for project in "${projects[@]}"; do
        git clean -f "p/$project/v".* &>/dev/null
    done

    git restore "p/ALL".* &>/dev/null
fi

exit $status
