#!/usr/bin/env bash

# Generate a report of the run, once it's completed

command -v git &>/dev/null || {
    echo 'Missing `git` -- cannot continue'
    exit 1
}

. lib/vars

shopt -s globstar
shopt -s nullglob

set -u

readarray -t projects < <(git status --porcelain=v1 -u all p/**/v.tsv | sed -e 's,^...p/,,' -e 's,/v.tsv$,,')

for project in "${projects[@]}"; do
    desc="$(grep "^$project:" "$VAT_TARGET/report")"
    git add "p/$project/v".*
    git commit -m "auto(p): update versions for $project" -m "$desc"
done

desc="$(<"$VAT_TARGET/report")"
git add "p/ALL.tsv"
git commit -m "auto(p): update versions for all projects" -m "$desc"
