#!/usr/bin/env bash

# Record the results of a run once it's completed

. lib/vars

retrieve_old_version() {
    local file="$VAT_ROOT/p/$project/v.tsv"

    if ! [ -f "$file" ]; then
        echo "Attempted to retrieve fallback version from nonexistent $file" >&2
        exit 1
    fi

    grep "^$channel"$'\t' "$file" | cut -f2
}

# Serialize raw data to TSV
write_tsv() {
    local file="$VAT_ROOT/p/$project/v.tsv"

    # Remove old versions
    if [ -f "$file" ]; then
        grep -vF "$project	$channel	" "$file" > "$file.tmp"
        mv "$file.tmp" "$file"
    fi

    printf "$project\t$channel\t$version\n" >> "$file"
}

# Reserialize the TSV data to JSON
write_json() {
    local tsv_file="$VAT_ROOT/p/$project/v.tsv"
    local json_file="$VAT_ROOT/p/$project/v.json"

    jq --indent 4 -Rs '
      split("\n")[:-1]
      | map(split("\t"))
      | map({project: .[0], channel: .[1], version: .[2]})
    ' "$tsv_file" > "$json_file"
}

# we only care about keys, but we don't want duplicates
declare -A projects
while IFS= read -r line; do
    IFS=$'\t' read -r project channel version <<< "$line"

    case "$version" in
        FAIL|SKIP) version=$(retrieve_old_version) ;;
    esac

    write_tsv
    projects["$project"]=_
done < "$VAT_TARGET/logs/ALL.out"

for project in "${!projects[@]}"; do
    write_json
done

${DRY:?} && return

cp -f "$VAT_TARGET/logs/ALL.out" p/ALL.tsv

# HACK: This is kind of horrible but I'm not very good at `jq`. If you have a
# better solution, please send it my way!
jq -s '.[]' p/**/v.json | sed -e '/^\]$/d' -e '/^\[$/d' -e 's/},/}/' | jq -s '.' > p/ALL.json
