#!/usr/bin/env bash

# Record the results of a run once it's completed

. lib/vars

shopt -s globstar

retrieve_old_version() {
    local file="$VAT_ROOT/p/$project/v.tsv"

    if ! [ -f "$file" ]; then
        echo "ERROR: Attempted to retrieve fallback version from nonexistent $file" >&2
        exit 1
    fi

    grep "^$project"$'\t'"$channel"$'\t' "$file" | cut -f3
}

# Serialize raw data to TSV
write_tsv() {
    local file="$VAT_ROOT/p/$project/v.tsv"

    # Remove old versions
    if [ -f "$file" ]; then
        grep -vF "$project	$channel	" "$file" > "$file.tmp"
        mv "$file.tmp" "$file"
    fi

    printf "$project\t$channel\t$version\n" >> "$file"
}

# Reserialize the TSV data to JSON
write_json() {
    local tsv_file="$VAT_ROOT/p/$project/v.tsv"
    local json_file="$VAT_ROOT/p/$project/v.json"

    declare -A entries

    {
        while IFS= read -r line; do
            IFS=$'\t' read -r _ channel version <<< "$line"
            entries["$channel"]="$version"
        done < "$tsv_file"

        printf '{ "%s": {\n' "$project"

        local len="${#entries[@]}"
        local ct=0
        for entry in "${!entries[@]}"; do
            ((ct++))
            if [ $ct -eq $len ]; then
                printf '"%s": "%s"\n' "${entry}" "${entries["$entry"]}"
            else
                printf '"%s": "%s",\n' "${entry}" "${entries["$entry"]}"
            fi
        done

        printf '} }\n'
    } | jq --indent 4 . > "$json_file"

    unset entries
}

# We only care about keys, but we don't want duplicates
declare -A projects

while IFS= read -r line; do
    IFS=$'\t' read -r project channel version <<< "$line"

    [ -z "$version" ] && continue

    case "$version" in
        FAIL|SKIP|TIME) version=$(retrieve_old_version) ;;
    esac

    [ -z "$version" ] && continue

    write_tsv
    projects["$project"]=_
done < "$VAT_TARGET/logs/ALL.out"

for project in "${!projects[@]}"; do
    write_json
done

unset projects

cat p/**/v.tsv > p/ALL.tsv

# HACK: I'm sure there's a correct way to do this, but I don't know it
{
    printf '{\n'
    sed '/^[\{\}]/d' p/**/v.json | sed -e '$d' -e 's/}/&,/'
    printf '}}\n'
} | jq --indent 4 . > p/ALL.json
