#!/usr/bin/env bash

# Generate a report of the run, once it's completed

command -v git &>/dev/null || {
    echo 'Missing `git` -- cannot continue'
    exit 1
}

. lib/vars

projects_updated=$(git status --porcelain=v1 -u all p | grep -vF ALL | cut -d/ -f2 | uniq | wc -l)

shopt -s globstar
set -u

elapsed_ms=$(<"$VAT_TARGET/elapsed")
hours=$((elapsed_ms / 3600000))
minutes=$((elapsed_ms % 3600000 / 60000))
seconds=$((elapsed_ms % 60000 / 1000))
millis=$((elapsed_ms % 1000))

if (( hours > 0 )); then
    printf -v elapsed "%02d:%02d:%02d.%03dms" "$hours" "$minutes" "$seconds" "$millis"
elif (( minutes > 0 )); then
    printf -v elapsed "%02d:%02d.%03d" "$minutes" "$seconds" "$millis"
else
    printf -v elapsed "%d.%03d seconds" "$seconds" "$millis"
fi

cat << .
[ VAT $(<version) | $(date +"%Y-%m-%d %H:%M:%S %Z") | #$(<runcount) ]

Processed $(cat "$VAT_TARGET/logs/ALL.out" | wc -l) channels for $# projects in $elapsed
    - Succeeded: $(grep -Evc '\s(SKIP|FAIL|TIME)$' "$VAT_TARGET/logs/ALL.out")
    - Skipped: $(grep -c '\sSKIP$' "$VAT_TARGET/logs/ALL.out")
    - Timed out: $(grep -c '\sTIME$' "$VAT_TARGET/logs/ALL.out")
    - Failed: $(grep -c '\sFAIL$' "$VAT_TARGET/logs/ALL.out")

New versions:
.

fmt() {
    local re="[a-f0-9]{40}"
    if [[ $1 =~ $re ]]; then
        echo "${1:0:8}"
    else
        echo "$1"
    fi
}

for project in "$@"; do
    git add "p/$project"
done

diff="$(git diff --staged -U0 --word-diff=plain --no-color -- p/**/v.tsv | sed -r '/^(index|---|\+\+\+|@@|new file mode) /d')"
while read -r line; do
    [ -z "$line" ] && continue

    # diff --git a/p/7zip/v.tsv b/p/7zip/v.tsv
    # determine project
    if [[ $line == *"diff --git a/p/"* ]]; then
        project="$(echo "$line" | cut -d\  -f3)"
        project="${project%/v.tsv}"
        project="${project#a/p/}"
        continue
    fi

    # unexpected line
    if ! [[ $line == *$'\t'* && $line == *'+}'* ]]; then
        # This is mostly just for debugging purposes
        # echo "WARNING: Found unexpected line '$line'"
        continue
    fi

    # release	[-26.00-]{+26.01+}
    # new version
    if [[ $line == *$'\t[-'* ]];  then
        l=$(echo "$line" | sed 's,-]{+,'$'\t',)
        l=$(echo "$l" | tr -d '+}[-')
        IFS=$'\t' read -r _ channel old new <<< "$l"

        if [ -z "$old$new" ]; then
            echo "WARNING: Missing old and new versions for $project:$channel" >&2
            continue
        fi

        if [ -z "$old" ]; then
            echo "WARNING: Missing old version for $project:$channel" >&2
            continue
        fi

        if [ -z "$new" ]; then
            echo "WARNING: Missing new version for $project:$channel" >&2
            continue
        fi

        printf -- "    - %-57s\t$(fmt $old) -> $(fmt $new)\n" "$project:$channel"
        continue
    fi

    # {+release	1.2.0+}
    # new channel
    if [[ $line == "{+"* ]]; then
        l=$(echo "$line" | tr -d '+}{')
        IFS=$'\t' read -r _ channel new <<< "$l"

        if [ -z "$new" ]; then
            echo "WARNING: Missing new version for $project:$channel" >&2
            continue
        fi

        printf -- "    - %-57s\t$(fmt $new)\n" "$project:$channel"
        continue
    fi
done <<< "$diff"
git restore --staged p
