#!/usr/bin/env bash
# shellcheck disable=2329

set -u

. lib/base || {
    echo "Could not source base library" >&2
    exit 2
}

project="$1"
name="${project##*/}"

. "p/$project/config" || {
    echo "Could not source config for $1" >&2
    exit 2
}

upstream_type() {
    case "$upstream" in
        *archlinux.org*) echo arch ;;
        *metacpan.org*) echo cpan ;;
        *pypi.org*) echo pypi ;;
        *sourceforge.net/projects/*) echo sf ;;
        */\?C=M?O=D) echo curl ;;
        *) echo git ;;
    esac
}

upstream_is_curl() {
    local re="/\?C=M[;&]O=D"
    [[ $upstream =~ $re ]]
}

roll_dice() {
    if "${GUARANTEE:?}"; then
        echo "Chance guaranteed" >&3
        return 0
    fi

    if [ -z "$(grep "$channel" "./p/$project/v.tsv" 2>/dev/null | cut -f3)" ]; then
        echo "$project:$channel has no fallback version; continuing" >&3
        return 0
    fi

    rand="$((RANDOM % 101))"
    if [ $rand -gt "${chance:-100}" ]; then
        echo "Chance $rand > ${chance:-100}; skipping" >&3
        return 77
    fi

    echo "Chance $rand < ${chance:-100}; continuing" >&3
    return 0
}

set_default_expected() {
    [ -n "${expected-}" ] && return
    case "$channel" in
        release) expected='[0-9]+(\.[0-9]+)*' ;;
        unstable) expected='[0-9]+(\.[0-9]+)*-?(rc|alpha|beta|a|b|pre|dev)?\.?[0-9]*' ;;
        commit) expected='[0-9a-f]{40}' ;;
    esac

    if [[ "$channel" =~ ^[0-9]+$ ]]; then
        expected="$channel"'(\.[0-9]+)*'
    fi
}

expand_upstream_shortforms() {
    printf "Expanded %s to " "$upstream" >&3
    upstream="$(echo "$upstream" | sed -f "$VAT_TARGET/shortforms.sed")"
    echo "$upstream" >&3
}

set_default_fetch() {
    type -t fetch | grep -qxF function && return

    # Handle numeric channels for supported upstreams
    if [[ "$channel" =~ ^[0-9]+$ ]]; then
        case "$(upstream_type)" in
            git)  fetch() { defgitchannel; }  ;;
            curl) fetch() { defcurlchannel; } ;;
        esac
        return
    fi

    case "$(upstream_type)/$channel" in
        git/release)    fetch() { defgitrelease; }      ;;
        git/unstable)   fetch() { defgitunstable; }     ;;
        git/commit)     fetch() { defgitcommit; }       ;;

        curl/release)   fetch() { defcurlrelease; }     ;;
        curl/unstable)  fetch() { defcurlunstable; }    ;;
        curl/commit)    fetch() { defcurlcommit; }      ;;

        arch/release)   fetch() { archver; }            ;;
        cpan/release)   fetch() { cpanver; }            ;;
        pypi/release)   fetch() { pypiver; }            ;;
        sf/release)     fetch() { sfver; }              ;;
    esac
}

set_default_compare() {
    [ -n "${compare-}" ] && return
    compare=true
    case "$channel" in
        commit) compare=false ;;
    esac
}

eval_result() {
    case $? in
        124) echo TIME; return 124 ;;
        77)  echo SKIP; return 77  ;;
        0)              return 0   ;;
        *)   echo FAIL; return 1   ;;
    esac
}

declare -a channels
readarray -t channels < <(declare -f | grep -x ':.\+ \(\)' | tr -d ': ()')

timeout() {
    local secs="${1:?}"
    shift

    # Silence job control output through redirectionanigans
    { "$@" 2>&3 & } 3>&2 2>&-
    local cmd_pid="$!"

    { sleep "$secs" 2>&3 & } 3>&2 2>&-
    local sleep_pid="$!"

    wait -n "$cmd_pid" "$sleep_pid" &>/dev/null
    local finished="$?"

    if kill -0 "$cmd_pid" &>/dev/null; then
        kill "$cmd_pid" &>/dev/null
        wait "$cmd_pid" &>/dev/null
        return 124
    fi

    kill "$sleep_pid" &>/dev/null
    return "$finished"
}

for channel in "${channels[@]}"; do
    (
        printf "%s\t%s\t" "$project" "$channel"

        type ":$channel" >&3
        ":$channel"
        roll_dice
        eval_result || exit

        expand_upstream_shortforms

        set_default_fetch
        type fetch >&3
        out=$(timeout 30 fetch | tail -n128)
        eval_result || exit

        echo "$out" | tail -n32 >&3
        ver="$(echo "$out" | tail -n1)"

        if [[ -z $ver ]]; then
            echo FAIL
            echo "Empty version for $project:$channel" >&2
            exit 1
        fi

        set_default_expected
        echo "expected is set to '$expected'" >&3

        if ! [[ $ver =~ ^$expected$ ]]; then
            echo FAIL
            echo "Version '$ver' does not match regex '$expected' for $project:$channel" >&2
            exit 1
        fi

        set_default_compare
        echo "compare is set to '$compare'" >&3
        if "$compare"; then
            old_ver="$(grep -F "	$channel	" "$VAT_ROOT/p/$project/v.tsv" 2>/dev/null | cut -f3)"
            if [ -n "${old_ver-}" ]; then
                greater="$(printf '%s\n%s\n' "$old_ver" "$ver" | versort | tail -n1)"
                if [[ "$greater" != "$ver" ]]; then
                    echo FAIL
                    echo "Version '$ver' is less than '$old_ver' for $project:$channel" >&2
                    exit 1
                fi
            fi
        fi

        echo "$ver"
    )
done
