#!/usr/bin/env bash

# Generate a tag and release assets for the run, once it's completed

command -v git &>/dev/null || {
    echo 'Missing `git` -- cannot continue' >&2
    exit 1
}

command -v gh &>/dev/null || {
    echo 'Missing `gh` -- cannot continue' >&2
    exit 1
}

. lib/vars

shopt -s globstar
set -u

projects=$(git status --porcelain=v1 -u all p/**/v.tsv | sed -e 's,^p/,,' -e 's,/v.tsv$,,')

rm -rf "$VAT_TARGET/dist"
mkdir -p "$VAT_TARGET/dist"
cp -f "$VAT_TARGET/report" "$VAT_TARGET/dist/report"
cp -f "$VAT_TARGET/logs/ALL."* "$VAT_TARGET/dist/"
xz -9e "$VAT_TARGET/dist/ALL."*

runcount="$(<runcount)"
version="$(<version)"

(
    echo "Archiving logs"
    cd "$VAT_TARGET"
    tar --numeric-owner --transform "s,logs,logs-$version-$runcount," -cJf "$VAT_TARGET/dist/logs.tar.xz" "logs"
    echo "Archiving projects"
    cd "$VAT_ROOT"
    tar --numeric-owner --transform "s,p,p-$version-$runcount,"       -cJf "$VAT_TARGET/dist/p.tar.xz"    "p"
)

git tag "run-$runcount" -m "$(<$VAT_TARGET/report)"
git push
git push --tags
gh release create "VAT $version run #$runcount" --notes-from-tag --latest=false "$VAT_TARGET/dist/"*
